name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Extract ZIP to a clean folder
      run: |
        mkdir game_folder
        unzip -q endless-car-racer-android.zip -d game_folder

    - name: Build APK
      run: |
        cd game_folder
        cd $(dirname $(find . -name "gradlew" | head -n 1))
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: EndlessCarRacer-APK
        path: "**/*.apk"
        
